output: .

collections:
  - common
  - typescript

excludes:
  - .cspell.json

render_context:
  name: quick-grunt
  description: Declarative grunt abstractions.
  author: joellefkowitz
  codacy_id: 0bf54bb20a744bec9c3d36ac206a0f3d
  keywords:
    - grunt
